import { StyleSheet } from 'react-native';
import { UCA_BLUE } from '../../../utils/constants';

export const styles = StyleSheet.create({
    topBar: {
        zIndex: 10,
        //position: 'relative',
        width: '100%',
        alignSelf: 'center',
        paddingTop: 5,
        backgroundColor: UCA_BLUE,
        elevation: 20,
        paddingBottom: 10,
        flexDirection: 'row',
    },
    searchBarHome: {
        flex: 1,
        alignSelf: 'center',
        position: 'absolute',
        elevation: 3,
        width: '80%',
        height: 90,
        top: -40,
    },
    boxLabel: {
        color: 'rgb(0,53,108)',
        fontFamily: 'Nunito-Bold',
        marginTop: 10,
        marginBottom: 2,
    },
    defaultPicker: {
        borderRadius: 10,
        height: 50,
        backgroundColor: 'rgb(0,53,108)',
        width: '90%',
        alignSelf: 'center',
    },
    searchResultsHome: {
        backgroundColor: 'rgb(245,245,248)',
        position: 'absolute',
        flex: 1,
        width: '100%',
        alignSelf: 'center',
        zIndex: 11,
    },
    searchResultsItem: {
        backgroundColor: 'rgb(200, 200, 200)',
        flex: 1,
        flexDirection: 'row',
        borderRadius: 10,
        bottom: '2.5%',
        width: '95%',
        height: 80,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.34,
        shadowRadius: 6.27,
        elevation: 5,
    },
    searchBarContainer: {
        backgroundColor: 'rgba(245,245,248, 0.5)',
        borderBottomColor: 'transparent',
        borderTopColor: 'transparent',
    },
    searchResultsImage: {
        height: '80%',
        margin: 5,
        marginHorizontal: 8,
    },
    searchResultsContainer: { flexDirection: 'row', alignSelf: 'center', width: '100%', justifyContent: 'space-between', alignContent: 'space-between' },
    numberOfTripsCircleIndicator: { borderRadius: 50, margin: 5, backgroundColor: '#EBF2FF', width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
    tripNumberIndicator: { fontFamily: 'Nunito-Bold', fontSize: 22, color: 'grey' },
    datePicker: { height: 53, justifyContent: 'center', alignSelf: 'center', margin: 5, backgroundColor: 'rgb(0,53,108)', width: '90%', borderRadius: 15 },
    radiusPicker: { height: 27, color: 'white', borderRadius: 15, overflow: 'hidden' },
    AMBAContainer: {
        height: 50,
        marginVertical: 5,
    },
    container: {
        alignSelf: 'center',
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 55,
    },
    map: { minHeight: 100, minWidth: 100, flex: 1, marginVertical: -15 },
    topBarItemsContainer: { flex: 1, flexDirection: 'row' },
    searchBarsContainer: { flex: 1, justifyContent: 'space-evenly' },
    addressFlipper: { justifyContent: 'center' },
    selectedTripAnimatedView: { position: 'absolute', zIndex: 10, width: '95%', alignSelf: 'center', opacity: 0.9 },
    defaultEdgePadding: { top: 50, bottom: 50, left: 50, right: 50 },
});
